# Generated by Django 2.1.7 on 2019-03-22 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lowLimit',
            field=models.IntegerField(default=20, verbose_name='quantity below which alert is shown for low stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracking.Category', verbose_name='category'),
        ),
    ]
