# Generated by Django 2.1.7 on 2019-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default=123, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
