# Generated by Django 2.1.7 on 2019-03-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracking', '0003_auto_20190319_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
